// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5G3ZIEQJFuWOZFMGcTtaK7KvE2Z8CLvg',
    appId: '1:1079604037728:android:752c4c2a96b1cbce8f9b05',
    messagingSenderId: '1079604037728',
    projectId: 'theta-bliss-417112',
    storageBucket: 'theta-bliss-417112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVEDHJqALUIzWE-XvnCyKBz1qju1eh84',
    appId: '1:1079604037728:ios:ab88a6ea28f3eb878f9b05',
    messagingSenderId: '1079604037728',
    projectId: 'theta-bliss-417112',
    storageBucket: 'theta-bliss-417112.appspot.com',
    androidClientId: '1079604037728-4ti1ginolormhirb8snp3t6ljj3bapul.apps.googleusercontent.com',
    iosClientId: '1079604037728-388rkbh18qro7ulo7uece27ra52bq1fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
